In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
print(arr.ndim)

[1 2 3 4 5]
(5,)
1


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
arr1 = np.array(42)
print(arr1)
print(arr1.shape)
print(arr1.ndim)

42
()
0


In [8]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [14]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)
print(arr3.shape)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
3


In [17]:
arr4 = np.array([1, 2, 3, 4], ndmin=5)
print(arr4)
print('number of dimensions :', arr4.ndim)
print(arr4.shape)


[[[[[1 2 3 4]]]]]
number of dimensions : 5
(1, 1, 1, 1, 4)


In [18]:
print(arr1,arr[0],arr2[0][1],arr3[0][1][2])

42 1 2 6


In [20]:
print(arr1,arr[0],arr2[0,1],arr3[0,1,2])

42 1 2 6


In [21]:
print(arr2,arr2[-2,-1])

[[1 2 3]
 [4 5 6]] 3


In [22]:
arr4 = np.array([1,2,3,4,5,6,7])
print(arr4[1:5])
print(arr4[-5:-1])

[2 3 4 5]
[3 4 5 6]


In [24]:
print(arr4[0:7:2])
print(arr4[::2])

[1 3 5 7]
[1 3 5 7]


In [25]:
arr5 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
print(arr5[1][1:4])
print(arr5[1,1:4])

[7 8 9]
[7 8 9]


In [28]:
print(arr5.dtype)

int32


In [29]:
arr6 = np.array(['apple','banana','cherry'])
print(arr6.dtype)

<U6


In [31]:
arr = np.array([1,2,3,4,5],dtype = 'U')
print(arr)
print(arr.dtype)

['1' '2' '3' '4' '5']
<U1


In [33]:
arr = np.array(['1','2','3'],dtype = 'i') 
print(arr) 
print(arr.dtype)

[1 2 3]
int32


In [34]:
arr = np.array(['a','2','3'],dtype = 'i')

ValueError: invalid literal for int() with base 10: 'a'

In [35]:
arr = np.array([3.447,2.141,4.15])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[3 2 4]
int32


In [39]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 43
print(arr)
print(x)

[43  2  3  4  5]
[1 2 3 4 5]


In [38]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [4]:
newarr2 = arr.reshape(2,3,2)
print(newarr2)
print(newarr2.shape)
print(newarr2.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
3


In [7]:
arr =np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

[1 2 3 4 5 6]
1
(6,)


In [9]:
arr = np.array([1,2,3],dtype='S')
for x in arr:
    print(x)

b'1'
b'2'
b'3'


In [12]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)
print()
for x in arr:
    for y in x:
        print(y)
print()
for x in arr:
    for y in x:
        for z in y:
            print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]

1
2
3
4
5
6
7
8
9
10
11
12


In [13]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [16]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1,arr2),axis = 1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [17]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10,11,12,13])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9]), array([10, 11, 12, 13])]


In [19]:
print(newarr[0])

[1 2 3]


In [22]:
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [23]:
arr2 = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr2))

[[2 3 4]
 [0 1 5]]


In [26]:
from numpy import random
x = random.randint(100)
print(x)

29


In [27]:
x1 = random.rand()
print(x1)

0.9646815095501043


In [28]:
x2 = random.randint(100,size=(3,5))
print(x2)

[[94 42 70 88  8]
 [97 78 50 52 89]
 [14 59  0 94 62]]


In [29]:
x3 = random.rand(3,5)
print(x3)

[[0.78020585 0.04692559 0.46360877 0.94667356 0.26741298]
 [0.41920753 0.37920802 0.07024287 0.36389095 0.77224424]
 [0.69428604 0.06551552 0.92051154 0.31924    0.59146284]]


In [30]:
a = np.array([[3, 2, 4], [5, 0, 1], [2, 5, 8]])
b = np.array([[1, 0, 5], [2, 3, 7], [6, 4, 5]])
print(a+2)
print(a-1)
print(a*5)

[[ 5  4  6]
 [ 7  2  3]
 [ 4  7 10]]
[[ 2  1  3]
 [ 4 -1  0]
 [ 1  4  7]]
[[15 10 20]
 [25  0  5]
 [10 25 40]]


In [32]:
a = np.array([[3, 2, 4], [5, 0, 1], [2, 5, 8]])
print(a)
ta = np.transpose(a)
print()
print(ta)

[[3 2 4]
 [5 0 1]
 [2 5 8]]

[[3 5 2]
 [2 0 5]
 [4 1 8]]


In [35]:
a = np.arange(5,50,2)
print(a)
print(np.mean(a))
print(np.std(a))
print(np.median(a))

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
27.0
13.2664991614216
27.0


In [36]:
print(np.min(a))
print(np.max(a))

5
49


In [37]:
a = np.array([[3, 2, 4], [10, 0, 1], [7, 5, 8]])
print(a)
print(np.min(a,axis = 0))
print(np.max(a,axis = 1))

[[ 3  2  4]
 [10  0  1]
 [ 7  5  8]]
[3 0 1]
[ 4 10  8]


In [38]:
from numpy import random
x = random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(100))
print(x)

[7 7 5 7 5 3 5 7 5 7 7 5 7 3 3 5 7 7 7 7 7 7 7 5 3 7 7 7 5 7 5 7 7 7 7 5 7
 7 7 5 5 7 5 5 7 5 5 7 7 5 5 7 5 3 7 5 7 7 5 7 7 7 3 3 7 7 3 7 5 7 3 7 7 3
 5 5 7 7 5 5 5 7 7 7 7 5 5 7 5 7 5 5 3 5 3 7 7 7 7 7]


In [40]:
y = random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(3,5))
print(y)

[[5 3 7 7 5]
 [7 7 7 7 7]
 [7 3 5 5 7]]


In [41]:
x = random.normal(size=(2,3))
print(x)

[[-0.18298843  0.90011202  0.54533223]
 [-0.60290441 -2.26354605 -0.34273733]]
